name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, bcmath, pdo_sqlite
        ini-values: post_max_size=256M, max_execution_time=300
        tools: composer

    - name: Check PHP Version and Extensions
      run: |
        php -v
        php -m

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"

    - name: Validate .env File
      run: |
        if [ ! -f .env ]; then echo ".env file is missing"; exit 1; fi

    - name: Install Dependencies
      run: composer install --verbose

    - name: Generate Application Key
      run: php artisan key:generate --verbose

    - name: Set Directory Permissions
      run: sudo chmod -R 777 storage bootstrap/cache

    - name: Create SQLite Database
      run: |
        mkdir -p database
        touch database/database.sqlite
        ls -la database/

    - name: Run Tests
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        APP_ENV: testing
      run: php artisan test --verbose

    - name: Debugging Step
      run: |
        set -e
        php artisan key:generate --verbose || { echo "Key generation failed"; exit 1; }
        php artisan test --verbose || { echo "Tests failed"; exit 1; }
